//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskCalculator.CalcResult {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcResult.CalServiceSoap")]
    public interface CalServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DeskCalculator.CalcResult.HelloWorldResponse HelloWorld(DeskCalculator.CalcResult.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.HelloWorldResponse> HelloWorldAsync(DeskCalculator.CalcResult.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Initialize", ReplyAction="*")]
        void Initialize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Initialize", ReplyAction="*")]
        System.Threading.Tasks.Task InitializeAsync();
        
        // CODEGEN: Generating message contract since element name firstNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        DeskCalculator.CalcResult.CalculationResponse Calculation(DeskCalculator.CalcResult.CalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.CalculationResponse> CalculationAsync(DeskCalculator.CalcResult.CalculationRequest request);
        
        // CODEGEN: Generating message contract since element name firstNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ButtonPressed", ReplyAction="*")]
        DeskCalculator.CalcResult.ButtonPressedResponse ButtonPressed(DeskCalculator.CalcResult.ButtonPressedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ButtonPressed", ReplyAction="*")]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.ButtonPressedResponse> ButtonPressedAsync(DeskCalculator.CalcResult.ButtonPressedRequest request);
        
        // CODEGEN: Generating message contract since element name sign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignPressed", ReplyAction="*")]
        DeskCalculator.CalcResult.SignPressedResponse SignPressed(DeskCalculator.CalcResult.SignPressedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignPressed", ReplyAction="*")]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.SignPressedResponse> SignPressedAsync(DeskCalculator.CalcResult.SignPressedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        double Sum(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        double Sub(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SubAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mult", ReplyAction="*")]
        double Mult(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mult", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Div", ReplyAction="*")]
        double Div(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Div", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DivAsync(double x, double y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DeskCalculator.CalcResult.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DeskCalculator.CalcResult.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculation", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.CalculationRequestBody Body;
        
        public CalculationRequest() {
        }
        
        public CalculationRequest(DeskCalculator.CalcResult.CalculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string signOperation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string secondNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string totalString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool fraction;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double result;
        
        public CalculationRequestBody() {
        }
        
        public CalculationRequestBody(string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            this.firstNumber = firstNumber;
            this.signOperation = signOperation;
            this.secondNumber = secondNumber;
            this.totalString = totalString;
            this.fraction = fraction;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculationResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.CalculationResponseBody Body;
        
        public CalculationResponse() {
        }
        
        public CalculationResponse(DeskCalculator.CalcResult.CalculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DeskCalculator.CalcResult.ArrayOfString CalculationResult;
        
        public CalculationResponseBody() {
        }
        
        public CalculationResponseBody(DeskCalculator.CalcResult.ArrayOfString CalculationResult) {
            this.CalculationResult = CalculationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ButtonPressedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ButtonPressed", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.ButtonPressedRequestBody Body;
        
        public ButtonPressedRequest() {
        }
        
        public ButtonPressedRequest(DeskCalculator.CalcResult.ButtonPressedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ButtonPressedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int digit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string signOperation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string secondNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string totalString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool fraction;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double result;
        
        public ButtonPressedRequestBody() {
        }
        
        public ButtonPressedRequestBody(int digit, string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            this.digit = digit;
            this.firstNumber = firstNumber;
            this.signOperation = signOperation;
            this.secondNumber = secondNumber;
            this.totalString = totalString;
            this.fraction = fraction;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ButtonPressedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ButtonPressedResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.ButtonPressedResponseBody Body;
        
        public ButtonPressedResponse() {
        }
        
        public ButtonPressedResponse(DeskCalculator.CalcResult.ButtonPressedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ButtonPressedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DeskCalculator.CalcResult.ArrayOfString ButtonPressedResult;
        
        public ButtonPressedResponseBody() {
        }
        
        public ButtonPressedResponseBody(DeskCalculator.CalcResult.ArrayOfString ButtonPressedResult) {
            this.ButtonPressedResult = ButtonPressedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignPressedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignPressed", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.SignPressedRequestBody Body;
        
        public SignPressedRequest() {
        }
        
        public SignPressedRequest(DeskCalculator.CalcResult.SignPressedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignPressedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string signOperation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string secondNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string totalString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool fraction;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double result;
        
        public SignPressedRequestBody() {
        }
        
        public SignPressedRequestBody(string sign, string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            this.sign = sign;
            this.firstNumber = firstNumber;
            this.signOperation = signOperation;
            this.secondNumber = secondNumber;
            this.totalString = totalString;
            this.fraction = fraction;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignPressedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignPressedResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeskCalculator.CalcResult.SignPressedResponseBody Body;
        
        public SignPressedResponse() {
        }
        
        public SignPressedResponse(DeskCalculator.CalcResult.SignPressedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignPressedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DeskCalculator.CalcResult.ArrayOfString SignPressedResult;
        
        public SignPressedResponseBody() {
        }
        
        public SignPressedResponseBody(DeskCalculator.CalcResult.ArrayOfString SignPressedResult) {
            this.SignPressedResult = SignPressedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalServiceSoapChannel : DeskCalculator.CalcResult.CalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalServiceSoapClient : System.ServiceModel.ClientBase<DeskCalculator.CalcResult.CalServiceSoap>, DeskCalculator.CalcResult.CalServiceSoap {
        
        public CalServiceSoapClient() {
        }
        
        public CalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeskCalculator.CalcResult.HelloWorldResponse DeskCalculator.CalcResult.CalServiceSoap.HelloWorld(DeskCalculator.CalcResult.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DeskCalculator.CalcResult.HelloWorldRequest inValue = new DeskCalculator.CalcResult.HelloWorldRequest();
            inValue.Body = new DeskCalculator.CalcResult.HelloWorldRequestBody();
            DeskCalculator.CalcResult.HelloWorldResponse retVal = ((DeskCalculator.CalcResult.CalServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.HelloWorldResponse> DeskCalculator.CalcResult.CalServiceSoap.HelloWorldAsync(DeskCalculator.CalcResult.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeskCalculator.CalcResult.HelloWorldResponse> HelloWorldAsync() {
            DeskCalculator.CalcResult.HelloWorldRequest inValue = new DeskCalculator.CalcResult.HelloWorldRequest();
            inValue.Body = new DeskCalculator.CalcResult.HelloWorldRequestBody();
            return ((DeskCalculator.CalcResult.CalServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void Initialize() {
            base.Channel.Initialize();
        }
        
        public System.Threading.Tasks.Task InitializeAsync() {
            return base.Channel.InitializeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeskCalculator.CalcResult.CalculationResponse DeskCalculator.CalcResult.CalServiceSoap.Calculation(DeskCalculator.CalcResult.CalculationRequest request) {
            return base.Channel.Calculation(request);
        }
        
        public DeskCalculator.CalcResult.ArrayOfString Calculation(string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            DeskCalculator.CalcResult.CalculationRequest inValue = new DeskCalculator.CalcResult.CalculationRequest();
            inValue.Body = new DeskCalculator.CalcResult.CalculationRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.signOperation = signOperation;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.totalString = totalString;
            inValue.Body.fraction = fraction;
            inValue.Body.result = result;
            DeskCalculator.CalcResult.CalculationResponse retVal = ((DeskCalculator.CalcResult.CalServiceSoap)(this)).Calculation(inValue);
            return retVal.Body.CalculationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.CalculationResponse> DeskCalculator.CalcResult.CalServiceSoap.CalculationAsync(DeskCalculator.CalcResult.CalculationRequest request) {
            return base.Channel.CalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeskCalculator.CalcResult.CalculationResponse> CalculationAsync(string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            DeskCalculator.CalcResult.CalculationRequest inValue = new DeskCalculator.CalcResult.CalculationRequest();
            inValue.Body = new DeskCalculator.CalcResult.CalculationRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.signOperation = signOperation;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.totalString = totalString;
            inValue.Body.fraction = fraction;
            inValue.Body.result = result;
            return ((DeskCalculator.CalcResult.CalServiceSoap)(this)).CalculationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeskCalculator.CalcResult.ButtonPressedResponse DeskCalculator.CalcResult.CalServiceSoap.ButtonPressed(DeskCalculator.CalcResult.ButtonPressedRequest request) {
            return base.Channel.ButtonPressed(request);
        }
        
        public DeskCalculator.CalcResult.ArrayOfString ButtonPressed(int digit, string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            DeskCalculator.CalcResult.ButtonPressedRequest inValue = new DeskCalculator.CalcResult.ButtonPressedRequest();
            inValue.Body = new DeskCalculator.CalcResult.ButtonPressedRequestBody();
            inValue.Body.digit = digit;
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.signOperation = signOperation;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.totalString = totalString;
            inValue.Body.fraction = fraction;
            inValue.Body.result = result;
            DeskCalculator.CalcResult.ButtonPressedResponse retVal = ((DeskCalculator.CalcResult.CalServiceSoap)(this)).ButtonPressed(inValue);
            return retVal.Body.ButtonPressedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.ButtonPressedResponse> DeskCalculator.CalcResult.CalServiceSoap.ButtonPressedAsync(DeskCalculator.CalcResult.ButtonPressedRequest request) {
            return base.Channel.ButtonPressedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeskCalculator.CalcResult.ButtonPressedResponse> ButtonPressedAsync(int digit, string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            DeskCalculator.CalcResult.ButtonPressedRequest inValue = new DeskCalculator.CalcResult.ButtonPressedRequest();
            inValue.Body = new DeskCalculator.CalcResult.ButtonPressedRequestBody();
            inValue.Body.digit = digit;
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.signOperation = signOperation;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.totalString = totalString;
            inValue.Body.fraction = fraction;
            inValue.Body.result = result;
            return ((DeskCalculator.CalcResult.CalServiceSoap)(this)).ButtonPressedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeskCalculator.CalcResult.SignPressedResponse DeskCalculator.CalcResult.CalServiceSoap.SignPressed(DeskCalculator.CalcResult.SignPressedRequest request) {
            return base.Channel.SignPressed(request);
        }
        
        public DeskCalculator.CalcResult.ArrayOfString SignPressed(string sign, string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            DeskCalculator.CalcResult.SignPressedRequest inValue = new DeskCalculator.CalcResult.SignPressedRequest();
            inValue.Body = new DeskCalculator.CalcResult.SignPressedRequestBody();
            inValue.Body.sign = sign;
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.signOperation = signOperation;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.totalString = totalString;
            inValue.Body.fraction = fraction;
            inValue.Body.result = result;
            DeskCalculator.CalcResult.SignPressedResponse retVal = ((DeskCalculator.CalcResult.CalServiceSoap)(this)).SignPressed(inValue);
            return retVal.Body.SignPressedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeskCalculator.CalcResult.SignPressedResponse> DeskCalculator.CalcResult.CalServiceSoap.SignPressedAsync(DeskCalculator.CalcResult.SignPressedRequest request) {
            return base.Channel.SignPressedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeskCalculator.CalcResult.SignPressedResponse> SignPressedAsync(string sign, string firstNumber, string signOperation, string secondNumber, string totalString, bool fraction, double result) {
            DeskCalculator.CalcResult.SignPressedRequest inValue = new DeskCalculator.CalcResult.SignPressedRequest();
            inValue.Body = new DeskCalculator.CalcResult.SignPressedRequestBody();
            inValue.Body.sign = sign;
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.signOperation = signOperation;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.totalString = totalString;
            inValue.Body.fraction = fraction;
            inValue.Body.result = result;
            return ((DeskCalculator.CalcResult.CalServiceSoap)(this)).SignPressedAsync(inValue);
        }
        
        public double Sum(double x, double y) {
            return base.Channel.Sum(x, y);
        }
        
        public System.Threading.Tasks.Task<double> SumAsync(double x, double y) {
            return base.Channel.SumAsync(x, y);
        }
        
        public double Sub(double x, double y) {
            return base.Channel.Sub(x, y);
        }
        
        public System.Threading.Tasks.Task<double> SubAsync(double x, double y) {
            return base.Channel.SubAsync(x, y);
        }
        
        public double Mult(double x, double y) {
            return base.Channel.Mult(x, y);
        }
        
        public System.Threading.Tasks.Task<double> MultAsync(double x, double y) {
            return base.Channel.MultAsync(x, y);
        }
        
        public double Div(double x, double y) {
            return base.Channel.Div(x, y);
        }
        
        public System.Threading.Tasks.Task<double> DivAsync(double x, double y) {
            return base.Channel.DivAsync(x, y);
        }
    }
}
